all: 111044014_AHMET_OZYILMAZ_HW1

111044014_AHMET_OZYILMAZ_HW1: main.o
	g++ main.o -o 111044014_AHMET_OZYILMAZ_HW1

main.o: main.cpp
	g++ -std=c++11 -c main.cpp

clean:
	rm *.o 111044014_AHMET_OZYILMAZ_HW1
